#!/bin/sh
if [ -f /etc/ppp/resolv.conf ]; then
	if [ -f /etc/ppp/resolv.prev ]; then
		cp -f /etc/ppp/resolv.prev /etc/resolv.conf
	else
		rm -f /etc/resolv.conf
	fi
fi

rm -f /etc/ppp/info.$IFNAME

if [ -x /bin/sysled ]; then
	/bin/sysled -i 0 2>/dev/null
fi

if [ -f /etc/ppp/rssi_decode.sh ]; then
	. /etc/ppp/rssi_decode.sh stop
fi
