#!/bin/sh
if [ -f /etc/ppp/resolv.conf ]; then
	rm -f /etc/ppp/resolv.prev
	if [ -f /etc/resolv.conf ]; then
		cp /etc/resolv.conf /etc/ppp/resolv.prev
		grep domain /etc/ppp/resolv.prev > /etc/resolv.conf
		grep search /etc/ppp/resolv.prev >> /etc/resolv.conf
		cat /etc/ppp/resolv.conf >> /etc/resolv.conf
	else
		cp /etc/ppp/resolv.conf /etc/.
	fi
fi

# set the txqueuelen higher than crappy 3
ifconfig $IFNAME txqueuelen 32 2>&1 > /dev/null

if [ -x /bin/sysled ]; then
	/bin/sysled -i 1 2>/dev/null
fi
if [ -f /etc/ppp/rssi_decode.sh ]; then
	. /etc/ppp/rssi_decode.sh start
fi

cat > /etc/ppp/info.$IFNAME << EOF
started = `cat /proc/uptime | cut -d '.' -f 1`
device = $DEVICE
ifname = $IFNAME
name = `sed '/^name /!d; s///; s/^"//; s/"$//; q' /etc/ppp/options`
iplocal = $IPLOCAL
ipremote = $IPREMOTE
dns1 = $DNS1
dns2 = $DNS2
peername = $PEERNAME
linkname = $LINKNAME
EOF
