(function(C){function ya(A,v,K){function V(a){E=Z(a);$();I()}function Z(a){for(var d=[],c=0;c<a.length;++c){var b;if(a[c].data){b={};for(var e in a[c])b[e]=a[c][e]}else b={data:a[c]};d.push(b)}return d}function W(a){C.extend(true,t,a);if(t.grid.borderColor==null)t.grid.borderColor=t.grid.color;if(t.xaxis.noTicks&&t.xaxis.ticks==null)t.xaxis.ticks=t.xaxis.noTicks;if(t.yaxis.noTicks&&t.yaxis.ticks==null)t.yaxis.ticks=t.yaxis.noTicks;if(t.grid.coloredAreas)t.grid.markings=t.grid.coloredAreas;if(t.grid.coloredAreasColor)t.grid.markingsColor=
t.grid.coloredAreasColor}function $(){var a,d=E.length,c=[],b=[];for(a=0;a<E.length;++a){var e=E[a].color;if(e!=null){--d;typeof e=="number"?b.push(e):c.push(J(E[a].color))}}for(a=0;a<b.length;++a)d=Math.max(d,b[a]+1);c=[];for(a=b=0;c.length<d;){e=t.colors.length==a?new L(100,100,100):J(t.colors[a]);var f=1+(b%2==1?-1:1)*Math.ceil(b/2)*0.2;e.scale(f,f,f);c.push(e);++a;if(a>=t.colors.length){a=0;++b}}for(a=d=0;a<E.length;++a){b=E[a];if(b.color==null){b.color=c[d].toString();++d}else if(typeof b.color==
"number")b.color=c[b.color].toString();b.lines=C.extend(true,{},t.lines,b.lines);b.points=C.extend(true,{},t.points,b.points);b.bars=C.extend(true,{},t.bars,b.bars);if(b.lines.show==null&&!b.bars.show&&!b.points.show)b.lines.show=true;if(b.shadowSize==null)b.shadowSize=t.shadowSize;if(!b.xaxis)b.xaxis=o.xaxis;if(b.xaxis==1)b.xaxis=o.xaxis;else if(b.xaxis==2)b.xaxis=o.x2axis;if(!b.yaxis)b.yaxis=o.yaxis;if(b.yaxis==1)b.yaxis=o.yaxis;else if(b.yaxis==2)b.yaxis=o.y2axis;if(!b.threshold)b.threshold=t.threshold;
b.subseries=null}}function I(){var a=Number.POSITIVE_INFINITY,d=Number.NEGATIVE_INFINITY,c,b,e,f,g;for(c in o){o[c].datamin=a;o[c].datamax=d;o[c].min=t[c].min;o[c].max=t[c].max;o[c].used=false}for(c=0;c<E.length;++c){g=E[c];g.datapoints={points:[],incr:2};var m=g.data,s=g.datapoints.points,p=g.xaxis,q=g.yaxis,w=a,x=d,h=a,j=d,k,r,u,B,aa=[];if(g.bars.show){g.datapoints.incr=3;aa.push({d:0})}p.used=q.used=true;B=g.datapoints.incr;for(b=e=0;b<m.length;++b,e+=B){u=m[b];r=k=null;if(m[b]!=null){k=u[0];r=
u[1]}if(k!=null&&!isNaN(k=+k)){if(k<w)w=k;if(k>x)x=k}else k=null;if(r!=null&&!isNaN(r=+r)){if(r<h)h=r;if(r>j)j=r}else r=null;if(k==null||r==null)k=r=null;for(f=2;f<B;++f)s[e+f]=u[f]==null?aa[f-2].d:u[f];s[e+1]=r;s[e]=k}if(g.bars.show){b=g.bars.align=="left"?0:-g.bars.barWidth/2;if(g.bars.horizontal){h+=b;j+=b+g.bars.barWidth}else{w+=b;x+=b+g.bars.barWidth}}p.datamin=Math.min(p.datamin,w);p.datamax=Math.max(p.datamax,x);q.datamin=Math.min(q.datamin,h);q.datamax=Math.max(q.datamax,j);if(g.lines.show&&
g.lines.steps){u=[];for(b=e=0;b<s.length;b+=B,e+=B){k=s[b];r=s[b+1];if(b>0&&s[b-B]!=null&&k!=null&&s[b-B+1]!=r){u[e]=k;u[e+1]=s[b-B+1];e+=B}u[e]=k;u[e+1]=r}g.datapoints.linespoints=u}if(g.threshold){p=C.extend({},g);q=C.extend({},g);p.datapoints={points:[],incr:B};q.datapoints={points:[],incr:B};q.color=g.threshold.color;w=g.threshold.below;x=p.datapoints.points;h=q.datapoints.points;for(b=0;b<s.length;b+=B){k=s[b];r=s[b+1];u=r<w?h:x;u.push(k);u.push(r);for(f=2;f<B;++f)u.push(s[b+f])}if(g.lines.show){s=
g.datapoints.linespoints||s;x=[];h=[];u=x;for(b=0;b<s.length;b+=B){k=s[b];r=s[b+1];f=u;if(r!=null)u=r<w?h:x;if(u!=f&&k!=null&&b>0&&s[b-B]!=null){e=(k-s[b-B])/(r-s[b-B+1])*(w-r)+k;f.push(e);f.push(w);u.push(null);u.push(null);u.push(e);u.push(w)}u.push(k);u.push(r)}p.datapoints.linespoints=x;q.datapoints.linespoints=h}g.subseries=[p,q]}}}function T(){function a(d,c){var b=document.createElement("canvas");b.width=d;b.height=c;if(C.browser.msie)b=window.G_vmlCanvasManager.initElement(b);return b}M=F.width();
N=F.height();F.html("");F.css("position")=="static"&&F.css("position","relative");if(M<=0||N<=0)throw"Invalid dimensions for plot, width = "+M+", height = "+N;C.browser.msie&&window.G_vmlCanvasManager.init_(document);ba=C(a(M,N)).appendTo(F).get(0);n=ba.getContext("2d");ea=C(a(M,N)).css({position:"absolute",left:0,top:0}).appendTo(F).get(0);D=ea.getContext("2d");U=C([ea,ba]);if(t.selection.mode!=null||t.crosshair.mode!=null||t.grid.hoverable){U.each(function(){this.onmousemove=za});t.selection.mode!=
null&&U.mousedown(Aa)}t.crosshair.mode!=null&&U.mouseout(Ba);t.grid.clickable&&U.click(Ca)}function ia(){function a(c,b){Da(c,b);Ea(c,b);Fa(c,b);if(c==o.xaxis||c==o.x2axis){c.p2c=function(e){return(e-c.min)*c.scale};c.c2p=function(e){return c.min+e/c.scale}}else{c.p2c=function(e){return(c.max-e)*c.scale};c.c2p=function(e){return c.max-e/c.scale}}}for(var d in o)a(o[d],t[d]);Ga();Ha();Ia()}function Da(a,d){var c=d.min!=null?+d.min:a.datamin,b=d.max!=null?+d.max:a.datamax;if(c==Number.POSITIVE_INFINITY)c=
0;if(b==Number.NEGATIVE_INFINITY)b=1;if(b-c==0){var e=b==0?1:0.01;if(d.min==null)c-=e;if(d.max==null||d.min!=null)b+=e}else{e=d.autoscaleMargin;if(e!=null){if(d.min==null){c-=(b-c)*e;if(c<0&&a.datamin>=0)c=0}if(d.max==null){b+=(b-c)*e;if(b>0&&a.datamax<=0)b=0}}}a.min=c;a.max=b}function Ea(a,d){var c=(a.max-a.min)/(typeof d.ticks=="number"&&d.ticks>0?d.ticks:a==o.xaxis||a==o.x2axis?M/100:N/60),b,e,f;if(d.mode=="time"){var g={second:1E3,minute:6E4,hour:36E5,day:864E5,month:2592E6,year:525949.2*60*1E3};
f=[[1,"second"],[2,"second"],[5,"second"],[10,"second"],[30,"second"],[1,"minute"],[2,"minute"],[5,"minute"],[10,"minute"],[30,"minute"],[1,"hour"],[2,"hour"],[4,"hour"],[8,"hour"],[12,"hour"],[1,"day"],[2,"day"],[3,"day"],[0.25,"month"],[0.5,"month"],[1,"month"],[2,"month"],[3,"month"],[6,"month"],[1,"year"]];b=0;if(d.minTickSize!=null)b=typeof d.tickSize=="number"?d.tickSize:d.minTickSize[0]*g[d.minTickSize[1]];for(e=0;e<f.length-1;++e)if(c<(f[e][0]*g[f[e][1]]+f[e+1][0]*g[f[e+1][1]])/2&&f[e][0]*
g[f[e][1]]>=b)break;b=f[e][0];e=f[e][1];if(e=="year"){f=Math.pow(10,Math.floor(Math.log(c/g.year)/Math.LN10));c=c/g.year/f;b=c<1.5?1:c<3?2:c<7.5?5:10;b*=f}if(d.tickSize){b=d.tickSize[0];e=d.tickSize[1]}c=function(p){var q=[],w=p.tickSize[0],x=p.tickSize[1],h=new Date(p.min),j=w*g[x];x=="second"&&h.setUTCSeconds(X(h.getUTCSeconds(),w));x=="minute"&&h.setUTCMinutes(X(h.getUTCMinutes(),w));x=="hour"&&h.setUTCHours(X(h.getUTCHours(),w));x=="month"&&h.setUTCMonth(X(h.getUTCMonth(),w));x=="year"&&h.setUTCFullYear(X(h.getUTCFullYear(),
w));h.setUTCMilliseconds(0);j>=g.minute&&h.setUTCSeconds(0);j>=g.hour&&h.setUTCMinutes(0);j>=g.day&&h.setUTCHours(0);j>=g.day*4&&h.setUTCDate(1);j>=g.year&&h.setUTCMonth(0);var k=0,r=Number.NaN,u;do{u=r;r=h.getTime();q.push({v:r,label:p.tickFormatter(r,p)});if(x=="month")if(w<1){h.setUTCDate(1);var B=h.getTime();h.setUTCMonth(h.getUTCMonth()+1);var aa=h.getTime();h.setTime(r+k*g.hour+(aa-B)*w);k=h.getUTCHours();h.setUTCHours(0)}else h.setUTCMonth(h.getUTCMonth()+w);else x=="year"?h.setUTCFullYear(h.getUTCFullYear()+
w):h.setTime(r+j)}while(r<p.max&&r!=u);return q};f=function(p,q){p=new Date(p);if(d.timeformat!=null)return C.plot.formatDate(p,d.timeformat,d.monthNames);var w=q.tickSize[0]*g[q.tickSize[1]];q=q.max-q.min;fmt=w<g.minute?"%h:%M:%S":w<g.day?q<2*g.day?"%h:%M":"%b %d %h:%M":w<g.month?"%b %d":w<g.year?q<g.year?"%b":"%b %y":"%y";return C.plot.formatDate(p,fmt,d.monthNames)}}else{var m=d.tickDecimals,s=-Math.floor(Math.log(c)/Math.LN10);if(m!=null&&s>m)s=m;f=Math.pow(10,-s);c=c/f;if(c<1.5)b=1;else if(c<
3){b=2;if(c>2.25&&(m==null||s+1<=m)){b=2.5;++s}}else b=c<7.5?5:10;b*=f;if(d.minTickSize!=null&&b<d.minTickSize)b=d.minTickSize;if(d.tickSize!=null)b=d.tickSize;a.tickDecimals=Math.max(0,m!=null?m:s);c=function(p){var q=[],w=X(p.min,p.tickSize),x=0,h=Number.NaN,j;do{j=h;h=w+x*p.tickSize;q.push({v:h,label:p.tickFormatter(h,p)});++x}while(h<p.max&&h!=j);return q};f=function(p,q){return p.toFixed(q.tickDecimals)}}a.tickSize=e?[b,e]:b;a.tickGenerator=c;a.tickFormatter=C.isFunction(d.tickFormatter)?function(p,
q){return""+d.tickFormatter(p,q)}:f;if(d.labelWidth!=null)a.labelWidth=d.labelWidth;if(d.labelHeight!=null)a.labelHeight=d.labelHeight}function Fa(a,d){a.ticks=[];if(a.used){if(d.ticks==null)a.ticks=a.tickGenerator(a);else if(typeof d.ticks=="number"){if(d.ticks>0)a.ticks=a.tickGenerator(a)}else if(d.ticks){var c=d.ticks;if(C.isFunction(c))c=c({min:a.min,max:a.max});var b,e;for(b=0;b<c.length;++b){var f=null,g=c[b];if(typeof g=="object"){e=g[0];if(g.length>1)f=g[1]}else e=g;if(f==null)f=a.tickFormatter(e,
a);a.ticks[b]={v:e,label:f}}}if(d.autoscaleMargin!=null&&a.ticks.length>0){if(d.min==null)a.min=Math.min(a.min,a.ticks[0].v);if(d.max==null&&a.ticks.length>1)a.max=Math.min(a.max,a.ticks[a.ticks.length-1].v)}}}function Ga(){function a(e){if(e.labelWidth==null)e.labelWidth=M/6;if(e.labelHeight==null){labels=[];for(i=0;i<e.ticks.length;++i)(l=e.ticks[i].label)&&labels.push('<div class="tickLabel" style="float:left;width:'+e.labelWidth+'px">'+l+"</div>");e.labelHeight=0;if(labels.length>0){var f=C('<div style="position:absolute;top:-10000px;width:10000px;font-size:smaller">'+
labels.join("")+'<div style="clear:left"></div></div>').appendTo(F);e.labelHeight=f.height();f.remove()}}}function d(e){if(e.labelWidth==null||e.labelHeight==null){var f,g=[],m;for(f=0;f<e.ticks.length;++f)(m=e.ticks[f].label)&&g.push('<div class="tickLabel">'+m+"</div>");if(g.length>0){f=C('<div style="position:absolute;top:-10000px;font-size:smaller">'+g.join("")+"</div>").appendTo(F);if(e.labelWidth==null)e.labelWidth=f.width();if(e.labelHeight==null)e.labelHeight=f.find("div").height();f.remove()}if(e.labelWidth==
null)e.labelWidth=0;if(e.labelHeight==null)e.labelHeight=0}}a(o.xaxis);d(o.yaxis);a(o.x2axis);d(o.y2axis);var c=t.grid.borderWidth;for(i=0;i<E.length;++i)c=Math.max(c,2*(E[i].points.radius+E[i].points.lineWidth/2));y.left=y.right=y.top=y.bottom=c;var b=t.grid.labelMargin+t.grid.borderWidth;if(o.xaxis.labelHeight>0)y.bottom=Math.max(c,o.xaxis.labelHeight+b);if(o.yaxis.labelWidth>0)y.left=Math.max(c,o.yaxis.labelWidth+b);if(o.x2axis.labelHeight>0)y.top=Math.max(c,o.x2axis.labelHeight+b);if(o.y2axis.labelWidth>
0)y.right=Math.max(c,o.y2axis.labelWidth+b);G=M-y.left-y.right;H=N-y.bottom-y.top;o.xaxis.scale=G/(o.xaxis.max-o.xaxis.min);o.yaxis.scale=H/(o.yaxis.max-o.yaxis.min);o.x2axis.scale=G/(o.x2axis.max-o.x2axis.min);o.y2axis.scale=H/(o.y2axis.max-o.y2axis.min)}function ja(){Ja();for(var a=0;a<E.length;++a){var d=E[a];if(d.subseries)for(var c=0;c<d.subseries.length;++c)ka(d.subseries[c]);else ka(d)}}function ca(a,d){var c=d+"axis",b=d+"2axis",e,f;if(a[c]){e=o[c];f=a[c].from;a=a[c].to}else if(a[b]){e=o[b];
f=a[b].from;a=a[b].to}else{e=o[c];f=a[d+"1"];a=a[d+"2"]}if(f!=null&&a!=null&&f>a)return{from:a,to:f,axis:e};return{from:f,to:a,axis:e}}function Ja(){var a;n.save();n.clearRect(0,0,M,N);n.translate(y.left,y.top);if(t.grid.backgroundColor){n.fillStyle=la(t.grid.backgroundColor,H,0,"rgba(255, 255, 255, 0)");n.fillRect(0,0,G,H)}var d=t.grid.markings;if(d){if(C.isFunction(d))d=d({xmin:o.xaxis.min,xmax:o.xaxis.max,ymin:o.yaxis.min,ymax:o.yaxis.max,xaxis:o.xaxis,yaxis:o.yaxis,x2axis:o.x2axis,y2axis:o.y2axis});
for(a=0;a<d.length;++a){var c=d[a],b=ca(c,"x"),e=ca(c,"y");if(b.from==null)b.from=b.axis.min;if(b.to==null)b.to=b.axis.max;if(e.from==null)e.from=e.axis.min;if(e.to==null)e.to=e.axis.max;if(!(b.to<b.axis.min||b.from>b.axis.max||e.to<e.axis.min||e.from>e.axis.max)){b.from=Math.max(b.from,b.axis.min);b.to=Math.min(b.to,b.axis.max);e.from=Math.max(e.from,e.axis.min);e.to=Math.min(e.to,e.axis.max);if(!(b.from==b.to&&e.from==e.to)){b.from=b.axis.p2c(b.from);b.to=b.axis.p2c(b.to);e.from=e.axis.p2c(e.from);
e.to=e.axis.p2c(e.to);if(b.from==b.to||e.from==e.to){n.strokeStyle=c.color||t.grid.markingsColor;n.beginPath();n.lineWidth=c.lineWidth||t.grid.markingsLineWidth;n.moveTo(b.from,e.from);n.lineTo(b.to,e.to);n.stroke()}else{n.fillStyle=c.color||t.grid.markingsColor;n.fillRect(b.from,e.to,b.to-b.from,e.from-e.to)}}}}}n.lineWidth=1;n.strokeStyle=t.grid.tickColor;n.beginPath();c=o.xaxis;for(a=0;a<c.ticks.length;++a){d=c.ticks[a].v;if(!(d<=c.min||d>=o.xaxis.max)){n.moveTo(Math.floor(c.p2c(d))+n.lineWidth/
2,0);n.lineTo(Math.floor(c.p2c(d))+n.lineWidth/2,H)}}c=o.yaxis;for(a=0;a<c.ticks.length;++a){d=c.ticks[a].v;if(!(d<=c.min||d>=c.max)){n.moveTo(0,Math.floor(c.p2c(d))+n.lineWidth/2);n.lineTo(G,Math.floor(c.p2c(d))+n.lineWidth/2)}}c=o.x2axis;for(a=0;a<c.ticks.length;++a){d=c.ticks[a].v;if(!(d<=c.min||d>=c.max)){n.moveTo(Math.floor(c.p2c(d))+n.lineWidth/2,-5);n.lineTo(Math.floor(c.p2c(d))+n.lineWidth/2,5)}}c=o.y2axis;for(a=0;a<c.ticks.length;++a){d=c.ticks[a].v;if(!(d<=c.min||d>=c.max)){n.moveTo(G-5,
Math.floor(c.p2c(d))+n.lineWidth/2);n.lineTo(G+5,Math.floor(c.p2c(d))+n.lineWidth/2)}}n.stroke();if(t.grid.borderWidth){a=t.grid.borderWidth;n.lineWidth=a;n.strokeStyle=t.grid.borderColor;n.strokeRect(-a/2,-a/2,G+a,H+a)}n.restore()}function Ha(){function a(b,e){for(var f=0;f<b.ticks.length;++f){var g=b.ticks[f];!g.label||g.v<b.min||g.v>b.max||d.push(e(g,b))}}F.find(".tickLabels").remove();var d=['<div class="tickLabels" style="font-size:smaller;color:'+t.grid.color+'">'],c=t.grid.labelMargin+t.grid.borderWidth;
a(o.xaxis,function(b,e){return'<div style="position:absolute;top:'+(y.top+H+c)+"px;left:"+Math.round(y.left+e.p2c(b.v)-e.labelWidth/2)+"px;width:"+e.labelWidth+'px;text-align:center" class="tickLabel">'+b.label+"</div>"});a(o.yaxis,function(b,e){return'<div style="position:absolute;top:'+Math.round(y.top+e.p2c(b.v)-e.labelHeight/2)+"px;right:"+(y.right+G+c)+"px;width:"+e.labelWidth+'px;text-align:right" class="tickLabel">'+b.label+"</div>"});a(o.x2axis,function(b,e){return'<div style="position:absolute;bottom:'+
(y.bottom+H+c)+"px;left:"+Math.round(y.left+e.p2c(b.v)-e.labelWidth/2)+"px;width:"+e.labelWidth+'px;text-align:center" class="tickLabel">'+b.label+"</div>"});a(o.y2axis,function(b,e){return'<div style="position:absolute;top:'+Math.round(y.top+e.p2c(b.v)-e.labelHeight/2)+"px;left:"+(y.left+G+c)+"px;width:"+e.labelWidth+'px;text-align:left" class="tickLabel">'+b.label+"</div>"});d.push("</div>");F.append(d.join(""))}function ka(a){a.lines.show&&Ka(a);a.bars.show&&La(a);a.points.show&&Ma(a)}function Ka(a){function d(f,
g,m,s,p){var q=f.linespoints||f.points;f=f.incr;var w=null,x=null;n.beginPath();for(var h=f;h<q.length;h+=f){var j=q[h-f],k=q[h-f+1],r=q[h],u=q[h+1];if(!(j==null||r==null)){if(k<=u&&k<p.min){if(u<p.min)continue;j=(p.min-k)/(u-k)*(r-j)+j;k=p.min}else if(u<=k&&u<p.min){if(k<p.min)continue;r=(p.min-k)/(u-k)*(r-j)+j;u=p.min}if(k>=u&&k>p.max){if(u>p.max)continue;j=(p.max-k)/(u-k)*(r-j)+j;k=p.max}else if(u>=k&&u>p.max){if(k>p.max)continue;r=(p.max-k)/(u-k)*(r-j)+j;u=p.max}if(j<=r&&j<s.min){if(r<s.min)continue;
k=(s.min-j)/(r-j)*(u-k)+k;j=s.min}else if(r<=j&&r<s.min){if(j<s.min)continue;u=(s.min-j)/(r-j)*(u-k)+k;r=s.min}if(j>=r&&j>s.max){if(r>s.max)continue;k=(s.max-j)/(r-j)*(u-k)+k;j=s.max}else if(r>=j&&r>s.max){if(j>s.max)continue;u=(s.max-j)/(r-j)*(u-k)+k;r=s.max}if(j!=w||k!=x)n.moveTo(s.p2c(j)+g,p.p2c(k)+m);w=r;x=u;n.lineTo(s.p2c(r)+g,p.p2c(u)+m)}}n.stroke()}function c(f,g,m){var s=f.linespoints||f.points;f=f.incr;var p=Math.min(Math.max(0,m.min),m.max),q;q=0;for(var w=false,x=f;x<s.length;x+=f){var h=
s[x-f],j=s[x-f+1],k=s[x],r=s[x+1];if(w&&h!=null&&k==null){n.lineTo(g.p2c(q),m.p2c(p));n.fill();w=false}else if(!(h==null||k==null)){if(h<=k&&h<g.min){if(k<g.min)continue;j=(g.min-h)/(k-h)*(r-j)+j;h=g.min}else if(k<=h&&k<g.min){if(h<g.min)continue;r=(g.min-h)/(k-h)*(r-j)+j;k=g.min}if(h>=k&&h>g.max){if(k>g.max)continue;j=(g.max-h)/(k-h)*(r-j)+j;h=g.max}else if(k>=h&&k>g.max){if(h>g.max)continue;r=(g.max-h)/(k-h)*(r-j)+j;k=g.max}if(!w){n.beginPath();n.moveTo(g.p2c(h),m.p2c(p));w=true}if(j>=m.max&&r>=
m.max){n.lineTo(g.p2c(h),m.p2c(m.max));n.lineTo(g.p2c(k),m.p2c(m.max));q=k}else if(j<=m.min&&r<=m.min){n.lineTo(g.p2c(h),m.p2c(m.min));n.lineTo(g.p2c(k),m.p2c(m.min));q=k}else{var u=h,B=k;if(j<=r&&j<m.min&&r>=m.min){h=(m.min-j)/(r-j)*(k-h)+h;j=m.min}else if(r<=j&&r<m.min&&j>=m.min){k=(m.min-j)/(r-j)*(k-h)+h;r=m.min}if(j>=r&&j>m.max&&r<=m.max){h=(m.max-j)/(r-j)*(k-h)+h;j=m.max}else if(r>=j&&r>m.max&&j<=m.max){k=(m.max-j)/(r-j)*(k-h)+h;r=m.max}if(h!=u){q=j<=m.min?m.min:m.max;n.lineTo(g.p2c(u),m.p2c(q));
n.lineTo(g.p2c(h),m.p2c(q))}n.lineTo(g.p2c(h),m.p2c(j));n.lineTo(g.p2c(k),m.p2c(r));if(k!=B){q=r<=m.min?m.min:m.max;n.lineTo(g.p2c(k),m.p2c(q));n.lineTo(g.p2c(B),m.p2c(q))}q=Math.max(k,B)}}}if(w){n.lineTo(g.p2c(q),m.p2c(p));n.fill()}}n.save();n.translate(y.left,y.top);n.lineJoin="round";var b=a.lines.lineWidth,e=a.shadowSize;if(b>0&&e>0){n.lineWidth=e;n.strokeStyle="rgba(0,0,0,0.1)";d(a.datapoints,1,Math.sqrt((b/2+e/2)*(b/2+e/2)-1),a.xaxis,a.yaxis);n.lineWidth=e/2;d(a.datapoints,1,Math.sqrt((b/2+
e/4)*(b/2+e/4)-1),a.xaxis,a.yaxis)}n.lineWidth=b;n.strokeStyle=a.color;if(e=fa(a.lines,a.color,0,H)){n.fillStyle=e;c(a.datapoints,a.xaxis,a.yaxis)}b>0&&d(a.datapoints,0,0,a.xaxis,a.yaxis);n.restore()}function Ma(a){function d(f,g,m,s,p,q,w){var x=f.points;f=f.incr;for(var h=0;h<x.length;h+=f){var j=x[h],k=x[h+1];if(!(j==null||j<q.min||j>q.max||k<w.min||k>w.max)){n.beginPath();n.arc(q.p2c(j),w.p2c(k)+s,g,0,p,true);if(m){n.fillStyle=m;n.fill()}n.stroke()}}}n.save();n.translate(y.left,y.top);var c=a.lines.lineWidth,
b=a.shadowSize,e=a.points.radius;if(c>0&&b>0){b=b/2;n.lineWidth=b;n.strokeStyle="rgba(0,0,0,0.1)";d(a.datapoints,e,null,b+b/2,2*Math.PI,a.xaxis,a.yaxis);n.strokeStyle="rgba(0,0,0,0.2)";d(a.datapoints,e,null,b/2,2*Math.PI,a.xaxis,a.yaxis)}n.lineWidth=c;n.strokeStyle=a.color;d(a.datapoints,e,fa(a.points,a.color),0,2*Math.PI,a.xaxis,a.yaxis);n.restore()}function ma(a,d,c,b,e,f,g,m,s,p,q){var w,x,h,j;if(q){j=x=h=true;w=false;q=c;a=a;c=d+b;e=d+e;if(a<q){d=a;a=q;q=d;w=true;x=false}}else{w=x=h=true;j=false;
q=a+b;a=a+e;e=c;c=d;if(c<e){d=c;c=e;e=d;j=true;h=false}}if(!(a<m.min||q>m.max||c<s.min||e>s.max)){if(q<m.min){q=m.min;w=false}if(a>m.max){a=m.max;x=false}if(e<s.min){e=s.min;j=false}if(c>s.max){c=s.max;h=false}q=m.p2c(q);e=s.p2c(e);a=m.p2c(a);c=s.p2c(c);if(g){p.beginPath();p.moveTo(q,e);p.lineTo(q,c);p.lineTo(a,c);p.lineTo(a,e);p.fillStyle=g(e,c);p.fill()}if(w||x||h||j){p.beginPath();p.moveTo(q,e+f);w?p.lineTo(q,c+f):p.moveTo(q,c+f);h?p.lineTo(a,c+f):p.moveTo(a,c+f);x?p.lineTo(a,e+f):p.moveTo(a,e+
f);j?p.lineTo(q,e+f):p.moveTo(q,e+f);p.stroke()}}}function La(a){function d(b,e,f,g,m,s,p){var q=b.points;b=b.incr;for(var w=0;w<q.length;w+=b)q[w]!=null&&ma(q[w],q[w+1],q[w+2],e,f,g,m,s,p,n,a.bars.horizontal)}n.save();n.translate(y.left,y.top);n.lineWidth=a.bars.lineWidth;n.strokeStyle=a.color;var c=a.bars.align=="left"?0:-a.bars.barWidth/2;d(a.datapoints,c,c+a.bars.barWidth,0,a.bars.fill?function(b,e){return fa(a.bars,a.color,b,e)}:null,a.xaxis,a.yaxis);n.restore()}function fa(a,d,c,b){var e=a.fill;
if(!e)return null;if(a.fillColor)return la(a.fillColor,c,b,d);a=J(d);a.a=typeof e=="number"?e:0.4;a.normalize();return a.toString()}function Ia(){F.find(".legend").remove();if(t.legend.show){var a=[],d=false,c=t.legend.labelFormatter,b,e;for(i=0;i<E.length;++i){b=E[i];if(e=b.label){if(i%t.legend.noColumns==0){d&&a.push("</tr>");a.push("<tr>");d=true}if(c)e=c(e,b);a.push('<td class="legendColorBox"><div style="border:1px solid '+t.legend.labelBoxBorderColor+';padding:1px"><div style="width:12px;height:10px;border:1px;background-color: '+
b.color+';overflow:hidden"></div></div></td><td class="legendLabel">'+e+"</td>")}}d&&a.push("</tr>");if(a.length!=0){d='<table style="font-size:smaller;color:'+t.grid.color+'">'+a.join("")+"</table>";if(t.legend.container!=null)C(t.legend.container).html(d);else{a="";c=t.legend.position;b=t.legend.margin;if(b[0]==null)b=[b,b];if(c.charAt(0)=="n")a+="top:"+(b[1]+y.top)+"px;";else if(c.charAt(0)=="s")a+="bottom:"+(b[1]+y.bottom)+"px;";if(c.charAt(1)=="e")a+="right:"+(b[0]+y.right)+"px;";else if(c.charAt(1)==
"w")a+="left:"+(b[0]+y.left)+"px;";d=C('<div class="legend">'+d.replace('style="','style="position:absolute;'+a+";")+"</div>").appendTo(F);if(t.legend.backgroundOpacity!=0){c=t.legend.backgroundColor;if(c==null){c=t.grid.backgroundColor&&typeof t.grid.backgroundColor=="string"?t.grid.backgroundColor:Na(d);c=J(c).adjust(null,null,null,1).toString()}b=d.children();C('<div style="position:absolute;width:'+b.width()+"px;height:"+b.height()+"px;"+a+"background-color:"+c+';"> </div>').prependTo(d).css("opacity",
t.legend.backgroundOpacity)}}}}}function Oa(a,d,c){var b=t.grid.mouseActiveRadius,e=b*b+1,f=null,g,m;for(g=0;g<E.length;++g)if(c(E[g])){var s=E[g],p=s.xaxis,q=s.yaxis,w=s.datapoints.points,x=s.datapoints.incr,h=p.c2p(a),j=q.c2p(d),k=b/p.scale,r=b/q.scale;if(s.lines.show||s.points.show)for(m=0;m<w.length;m+=x){var u=w[m],B=w[m+1];if(u!=null)if(!(u-h>k||u-h<-k||B-j>r||B-j<-r)){u=Math.abs(p.p2c(u)-a);B=Math.abs(q.p2c(B)-d);B=u*u+B*B;if(B<e){e=B;f=[g,m/x]}}}if(s.bars.show&&!f){p=s.bars.align=="left"?
0:-s.bars.barWidth/2;s=p+s.bars.barWidth;for(m=0;m<w.length;m+=x){u=w[m];B=w[m+1];q=w[m+2];if(u!=null)if(E[g].bars.horizontal?h<=Math.max(q,u)&&h>=Math.min(q,u)&&j>=B+p&&j<=B+s:h>=u+p&&h<=u+s&&j>=Math.min(q,B)&&j<=Math.max(q,B))f=[g,m/x]}}}if(f){g=f[0];m=f[1];return{datapoint:E[g].data[m],dataIndex:m,series:E[g],seriesIndex:g}}return null}function za(a){a=a||window.event;if(a.pageX==null&&a.clientX!=null){var d=document.documentElement,c=document.body;P.pageX=a.clientX+(d&&d.scrollLeft||c.scrollLeft||
0)-(d.clientLeft||0);P.pageY=a.clientY+(d&&d.scrollTop||c.scrollTop||0)-(d.clientTop||0)}else{P.pageX=a.pageX;P.pageY=a.pageY}t.grid.hoverable&&na("plothover",P,function(b){return b.hoverable!=false});if(t.crosshair.mode!=null)if(z.active)Q.pos.x=-1;else{oa(Q.pos,P);R()}if(z.active){F.trigger("plotselecting",[da()?pa():null]);qa(P)}}function Aa(a){if(a.which==1){document.body.focus();if(document.onselectstart!==undefined&&Y.onselectstart==null){Y.onselectstart=document.onselectstart;document.onselectstart=
function(){return false}}if(document.ondrag!==undefined&&Y.ondrag==null){Y.ondrag=document.ondrag;document.ondrag=function(){return false}}ra(z.first,a);P.pageX=null;z.active=true;C(document).one("mouseup",Pa)}}function Ba(){if(t.crosshair.mode!=null&&Q.pos.x!=-1){Q.pos.x=-1;R()}}function Ca(a){if(ga)ga=false;else na("plotclick",a,function(d){return d.clickable!=false})}function na(a,d,c){var b=U.offset(),e={pageX:d.pageX,pageY:d.pageY},f=d.pageX-b.left-y.left;d=d.pageY-b.top-y.top;if(o.xaxis.used)e.x=
o.xaxis.c2p(f);if(o.yaxis.used)e.y=o.yaxis.c2p(d);if(o.x2axis.used)e.x2=o.x2axis.c2p(f);if(o.y2axis.used)e.y2=o.y2axis.c2p(d);if(c=Oa(f,d,c)){c.pageX=parseInt(c.series.xaxis.p2c(c.datapoint[0])+b.left+y.left);c.pageY=parseInt(c.series.yaxis.p2c(c.datapoint[1])+b.top+y.top)}if(t.grid.autoHighlight){for(b=0;b<O.length;++b){f=O[b];f.auto==a&&!(c&&f.series==c.series&&f.point==c.datapoint)&&sa(f.series,f.point)}c&&ta(c.series,c.datapoint,a)}F.trigger(a,[e,c])}function R(){ha||(ha=setTimeout(Qa,30))}function Qa(){ha=
null;D.save();D.clearRect(0,0,M,N);D.translate(y.left,y.top);var a,d;for(a=0;a<O.length;++a){d=O[a];d.series.bars.show?Ra(d.series,d.point):Sa(d.series,d.point)}if(z.show&&da()){D.strokeStyle=J(t.selection.color).scale(null,null,null,0.8).toString();D.lineWidth=1;n.lineJoin="round";D.fillStyle=J(t.selection.color).scale(null,null,null,0.4).toString();a=Math.min(z.first.x,z.second.x);d=Math.min(z.first.y,z.second.y);var c=Math.abs(z.second.x-z.first.x),b=Math.abs(z.second.y-z.first.y);D.fillRect(a,
d,c,b);D.strokeRect(a,d,c,b)}a=Q.pos;d=t.crosshair.mode;if(d!=null&&a.x!=-1){D.strokeStyle=J(t.crosshair.color).scale(null,null,null,0.8).toString();D.lineWidth=1;n.lineJoin="round";D.beginPath();if(d.indexOf("x")!=-1){D.moveTo(a.x,0);D.lineTo(a.x,H)}if(d.indexOf("y")!=-1){D.moveTo(0,a.y);D.lineTo(G,a.y)}D.stroke()}D.restore()}function ta(a,d,c){if(typeof a=="number")a=E[a];if(typeof d=="number")d=a.data[d];var b=ua(a,d);if(b==-1){O.push({series:a,point:d,auto:c});R()}else if(!c)O[b].auto=false}function sa(a,
d){if(typeof a=="number")a=E[a];if(typeof d=="number")d=a.data[d];a=ua(a,d);if(a!=-1){O.splice(a,1);R()}}function ua(a,d){for(var c=0;c<O.length;++c){var b=O[c];if(b.series==a&&b.point[0]==d[0]&&b.point[1]==d[1])return c}return-1}function Sa(a,d){var c=d[0];d=d[1];var b=a.xaxis,e=a.yaxis;if(!(c<b.min||c>b.max||d<e.min||d>e.max)){var f=a.points.radius+a.points.lineWidth/2;D.lineWidth=f;D.strokeStyle=J(a.color).scale(1,1,1,0.5).toString();a=1.5*f;D.beginPath();D.arc(b.p2c(c),e.p2c(d),a,0,2*Math.PI,
true);D.stroke()}}function Ra(a,d){D.lineWidth=a.bars.lineWidth;D.strokeStyle=J(a.color).scale(1,1,1,0.5).toString();var c=J(a.color).scale(1,1,1,0.5).toString(),b=a.bars.align=="left"?0:-a.bars.barWidth/2;ma(d[0],d[1],d[2]||0,b,b+a.bars.barWidth,0,function(){return c},a.xaxis,a.yaxis,D,a.bars.horizontal)}function oa(a,d){var c=U.offset();a.x=S(0,d.pageX-c.left-y.left,G);a.y=S(0,d.pageY-c.top-y.top,H)}function va(a){if(a==null)Q.pos.x=-1;else{Q.pos.x=S(0,a.x!=null?o.xaxis.p2c(a.x):o.x2axis.p2c(a.x2),
G);Q.pos.y=S(0,a.y!=null?o.yaxis.p2c(a.y):o.y2axis.p2c(a.y2),H)}R()}function pa(){var a=Math.min(z.first.x,z.second.x),d=Math.max(z.first.x,z.second.x),c=Math.max(z.first.y,z.second.y),b=Math.min(z.first.y,z.second.y),e={};if(o.xaxis.used)e.xaxis={from:o.xaxis.c2p(a),to:o.xaxis.c2p(d)};if(o.x2axis.used)e.x2axis={from:o.x2axis.c2p(a),to:o.x2axis.c2p(d)};if(o.yaxis.used)e.yaxis={from:o.yaxis.c2p(c),to:o.yaxis.c2p(b)};if(o.y2axis.used)e.y2axis={from:o.y2axis.c2p(c),to:o.y2axis.c2p(b)};return e}function wa(){var a=
pa();F.trigger("plotselected",[a]);o.xaxis.used&&o.yaxis.used&&F.trigger("selected",[{x1:a.xaxis.from,y1:a.yaxis.from,x2:a.xaxis.to,y2:a.yaxis.to}])}function Pa(a){if(document.onselectstart!==undefined)document.onselectstart=Y.onselectstart;if(document.ondrag!==undefined)document.ondrag=Y.ondrag;z.active=false;qa(a);if(da()){wa();ga=true}else{F.trigger("plotunselected",[]);F.trigger("plotselecting",[null])}return false}function ra(a,d){oa(a,d);if(t.selection.mode=="y")a.x=a==z.first?0:G;if(t.selection.mode==
"x")a.y=a==z.first?0:H}function qa(a){if(a.pageX!=null){ra(z.second,a);if(da()){z.show=true;R()}else xa(true)}}function xa(a){if(z.show){z.show=false;R();a||F.trigger("plotunselected",[])}}function Ta(a,d){var c;if(t.selection.mode=="y"){z.first.x=0;z.second.x=G}else{c=ca(a,"x");z.first.x=c.axis.p2c(c.from);z.second.x=c.axis.p2c(c.to)}if(t.selection.mode=="x"){z.first.y=0;z.second.y=H}else{c=ca(a,"y");z.first.y=c.axis.p2c(c.from);z.second.y=c.axis.p2c(c.to)}z.show=true;R();d||wa()}function da(){return Math.abs(z.second.x-
z.first.x)>=5&&Math.abs(z.second.y-z.first.y)>=5}function la(a,d,c,b){if(typeof a=="string")return a;else{d=n.createLinearGradient(0,c,0,d);c=0;for(var e=a.colors.length;c<e;++c){var f=a.colors[c];d.addColorStop(c/(e-1),typeof f=="string"?f:J(b).scale(f.brightness,f.brightness,f.brightness,f.opacity))}return d}}var E=[],t={colors:["#edc240","#afd8f8","#cb4b4b","#4da74d","#9440ed"],legend:{show:true,noColumns:1,labelFormatter:null,labelBoxBorderColor:"#ccc",container:null,position:"ne",margin:5,backgroundColor:null,
backgroundOpacity:0.85},xaxis:{mode:null,min:null,max:null,autoscaleMargin:null,ticks:null,tickFormatter:null,labelWidth:null,labelHeight:null,tickDecimals:null,tickSize:null,minTickSize:null,monthNames:null,timeformat:null},yaxis:{autoscaleMargin:0.02},x2axis:{autoscaleMargin:null},y2axis:{autoscaleMargin:0.02},points:{show:false,radius:3,lineWidth:2,fill:true,fillColor:"#ffffff"},lines:{lineWidth:2,fill:false,fillColor:null,steps:false},bars:{show:false,lineWidth:2,barWidth:1,fill:true,fillColor:null,
align:"left",horizontal:false},threshold:null,grid:{color:"#545454",backgroundColor:null,tickColor:"#dddddd",labelMargin:5,borderWidth:2,borderColor:null,markings:null,markingsColor:"#f4f4f4",markingsLineWidth:2,clickable:false,hoverable:false,autoHighlight:true,mouseActiveRadius:10},selection:{mode:null,color:"#e8cfac"},crosshair:{mode:null,color:"#aa0000"},shadowSize:3},ba=null,ea=null,U=null,n=null,D=null,F=C(A),o={xaxis:{},yaxis:{},x2axis:{},y2axis:{}},y={left:0,right:0,top:0,bottom:0},M=0,N=
0,G=0,H=0,Y={};this.setData=V;this.setupGrid=ia;this.draw=ja;this.clearSelection=xa;this.setSelection=Ta;this.parseOptions=W;this.getCanvas=function(){return ba};this.getPlotOffset=function(){return y};this.getData=function(){return E};this.getAxes=function(){return o};this.setCrosshair=va;this.clearCrosshair=function(){va(null)};this.highlight=ta;this.unhighlight=sa;W(K);V(v);T();ia();ja();var P={pageX:null,pageY:null},z={first:{x:-1,y:-1},second:{x:-1,y:-1},show:false,active:false},Q={pos:{x:-1,
y:-1}},O=[],ga=false,ha=null}function X(A,v){return v*Math.floor(A/v)}function S(A,v,K){return v<A?A:v>K?K:v}function L(){for(var A=["r","g","b","a"],v=4;-1<--v;)this[A[v]]=arguments[v]||(v==3?1:0);this.toString=function(){return this.a>=1?"rgb("+[this.r,this.g,this.b].join(",")+")":"rgba("+[this.r,this.g,this.b,this.a].join(",")+")"};this.scale=function(){for(v=4;-1<--v;)if(arguments[v]!=null)this[A[v]]*=arguments[v];return this.normalize()};this.adjust=function(){for(v=4;-1<--v;)if(arguments[v]!=
null)this[A[v]]+=arguments[v];return this.normalize()};this.clone=function(){return new L(this.r,this.b,this.g,this.a)};this.normalize=function(){this.r=S(0,parseInt(this.r),255);this.g=S(0,parseInt(this.g),255);this.b=S(0,parseInt(this.b),255);this.a=S(0,this.a,1);return this};this.normalize()}function Na(A){var v=A;do{A=v.css("background-color").toLowerCase();if(A!=""&&A!="transparent")break;v=v.parent()}while(!C.nodeName(v.get(0),"body"));if(A=="rgba(0, 0, 0, 0)")return"transparent";return A}function J(A){var v;
if(v=/rgb\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*\)/.exec(A))return new L(parseInt(v[1],10),parseInt(v[2],10),parseInt(v[3],10));if(v=/rgba\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]+(?:\.[0-9]+)?)\s*\)/.exec(A))return new L(parseInt(v[1],10),parseInt(v[2],10),parseInt(v[3],10),parseFloat(v[4]));if(v=/rgb\(\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*\)/.exec(A))return new L(parseFloat(v[1])*2.55,parseFloat(v[2])*
2.55,parseFloat(v[3])*2.55);if(v=/rgba\(\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\s*\)/.exec(A))return new L(parseFloat(v[1])*2.55,parseFloat(v[2])*2.55,parseFloat(v[3])*2.55,parseFloat(v[4]));if(v=/#([a-fA-F0-9]{2})([a-fA-F0-9]{2})([a-fA-F0-9]{2})/.exec(A))return new L(parseInt(v[1],16),parseInt(v[2],16),parseInt(v[3],16));if(v=/#([a-fA-F0-9])([a-fA-F0-9])([a-fA-F0-9])/.exec(A))return new L(parseInt(v[1]+v[1],16),parseInt(v[2]+
v[2],16),parseInt(v[3]+v[3],16));A=C.trim(A).toLowerCase();if(A=="transparent")return new L(255,255,255,0);else{v=Ua[A];return new L(v[0],v[1],v[2])}}C.plot=function(A,v,K){return new ya(A,v,K)};C.plot.formatDate=function(A,v,K){var V=function(T){T=""+T;return T.length==1?"0"+T:T},Z=[],W=false;if(K==null)K=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];for(var $=0;$<v.length;++$){var I=v.charAt($);if(W){switch(I){case "h":I=""+A.getUTCHours();break;case "H":I=V(A.getUTCHours());
break;case "M":I=V(A.getUTCMinutes());break;case "S":I=V(A.getUTCSeconds());break;case "d":I=""+A.getUTCDate();break;case "m":I=""+(A.getUTCMonth()+1);break;case "y":I=""+A.getUTCFullYear();break;case "b":I=""+K[A.getUTCMonth()];break}Z.push(I);W=false}else if(I=="%")W=true;else Z.push(I)}return Z.join("")};var Ua={aqua:[0,255,255],azure:[240,255,255],beige:[245,245,220],black:[0,0,0],blue:[0,0,255],brown:[165,42,42],cyan:[0,255,255],darkblue:[0,0,139],darkcyan:[0,139,139],darkgrey:[169,169,169],
darkgreen:[0,100,0],darkkhaki:[189,183,107],darkmagenta:[139,0,139],darkolivegreen:[85,107,47],darkorange:[255,140,0],darkorchid:[153,50,204],darkred:[139,0,0],darksalmon:[233,150,122],darkviolet:[148,0,211],fuchsia:[255,0,255],gold:[255,215,0],green:[0,128,0],indigo:[75,0,130],khaki:[240,230,140],lightblue:[173,216,230],lightcyan:[224,255,255],lightgreen:[144,238,144],lightgrey:[211,211,211],lightpink:[255,182,193],lightyellow:[255,255,224],lime:[0,255,0],magenta:[255,0,255],maroon:[128,0,0],navy:[0,
0,128],olive:[128,128,0],orange:[255,165,0],pink:[255,192,203],purple:[128,0,128],violet:[128,0,128],red:[255,0,0],silver:[192,192,192],white:[255,255,255],yellow:[255,255,0]}})(jQuery);
